### ISSUE TITLE
For enhancement, Icon/Logo Proposal

### ISSUE THREAD

**Issue by loydjayme25** [ardovic/Open-Weather-Android#19]
Good day ! can i submit my proposal for your project ?

**Comment by ardovic** [comment]
Hi. Yes of course. If you can please follow the FAQ guidelines. Open an
issue and I'll assign you to it. Then make a pull request with your changes.

**Comment by ardovic** [comment]
If you need any help, feel free to ask

**Comment by loydjayme25** [comment]
Thank you PO, i am currently making a design for your project.

**Comment by loydjayme25** [comment]
Suggestions are very open sir, the design is more likely a technology base logo.

![trial](https://user-images.githubusercontent.com/37318022/39735909-3afd9bd0-52b0-11e8-964a-cdcdb2e2769c.png)

**Comment by ardovic** [comment]
Loyd, wouldn't it be nice to have some resemblance to "weather" - maybe a sun or rain on the logo? Also, in the middle of android can you try putting the "open source logo"?

**Comment by ardovic** [comment]
I figured out that it would be good to have 3 things on the logo:

1) Weather
2) Android
3) Open source logo

Here's a small prototype I just made of what can be done -

**Comment by loydjayme25** [comment]
![new trial](https://user-images.githubusercontent.com/37318022/39744695-b7643f04-52d7-11e8-8c50-a286bdd3e1f1.png)

is this okay sir ?

**Comment by loydjayme25** [comment]
![image](https://user-images.githubusercontent.com/37318022/39744967-7cb64766-52d8-11e8-9340-fb70205e003a.png)

**Comment by ardovic** [comment]
The first one looks good. Do you know how to properly add this logo to the android project?

**Comment by loydjayme25** [comment]
i don't know how to do it sir.

**Comment by loydjayme25** [comment]
but i can send you the google drive link of all the design sir.

**Comment by ardovic** [comment]
Can you please follow the guide I've written on the main page (fork project -> add file -> make pull request)

**Comment by loydjayme25** [comment]
okay sir , noted ! Many Thanks !
